# Generated by Django 6.0.2 on 2026-03-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_instructor_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.CharField(default='video-link', max_length=500),
        ),
    ]
