# Generated by Django 6.0.2 on 2026-03-11 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_subcategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Category',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.subcategory'),
        ),
    ]
