# Generated by Django 6.0.2 on 2026-03-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_instructor_image_remove_instructor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
