# Generated by Django 6.0.2 on 2026-03-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_instructor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='image',
            field=models.ImageField(default='static/images/user-image', upload_to='static/images/instructor_images'),
        ),
    ]
