# Generated by Django 6.0.2 on 2026-03-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_instructor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='image',
            field=models.ImageField(default='static/images/profile-pic.png', upload_to='static/images/instructor_images'),
        ),
    ]
