# Generated by Django 6.0.2 on 2026-03-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_instructor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
