# Generated by Django 6.0.2 on 2026-03-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_course_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount',
            field=models.FloatField(default=86.67),
        ),
    ]
