# Generated by Django 6.0.2 on 2026-03-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pro_pic',
            field=models.ImageField(upload_to='images/profile_pictures/'),
        ),
    ]
